(asdf:oos 'asdf:load-op :iolib.syscalls)

(defmacro with-stopwatch (&body body)
  (let ((sec0 (gensym))
        (sec1 (gensym))
        (usec0 (gensym))
        (usec1 (gensym)))
    `(multiple-value-bind (,sec0 ,usec0)
         (isys:gettimeofday)
       (unwind-protect
            (progn ,@body))
       (multiple-value-bind (,sec1 ,usec1)
           (isys:gettimeofday)
         (+ (* 1e6 (- ,sec1 ,sec0))
            ,usec1 (- ,usec0))))))
